fulldata <- read.csv("household_power_consumption.txt", na.strings = "?", sep = ";")
dates <- ((fulldata[, 1] == "1/2/2007") | (fulldata[, 1] == "2/2/2007"))
interdata <- fulldata[dates, ]
datetime <- strptime(paste(interdata[, 1], interdata[, 2]), "%d/%m/%Y %H:%M:%S")
interdata[, 3] <- as.numeric(interdata[, 3])
interdata[, 4] <- as.numeric(interdata[, 4])
interdata[, 5] <- as.numeric(interdata[, 5])
interdata[, 7] <- as.numeric(interdata[, 7])
interdata[, 8] <- as.numeric(interdata[, 8])
interdata[, 9] <- as.numeric(interdata[, 9])
png(filename = "plot4.png")
par(mfrow = c(2,2))
plot(datetime, interdata[, 3], type = "n", ylab = "Global Active Power", xlab = "")
lines(datetime, interdata[, 3])
plot(datetime, interdata[, 5], type = "n", ylab = "Voltage")
lines(datetime, interdata[, 5])
plot(datetime, interdata[, 7], type = "n", ylab = "Energy sub metering", xlab = "")
lines(datetime, interdata[, 7])
lines(datetime, interdata[, 8], col = "red")
lines(datetime, interdata[, 9], col = "blue")
legend("topright", bty = "n", lwd = 1, col = c("black", "blue", "red"), legend = c(
    "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(datetime, interdata[, 4], type = "n", ylab = "Global_reactive_power")
lines(datetime, interdata[, 4])
dev.off()